### ISSUE TITLE
No examples to get started

### ISSUE THREAD

**Issue by MedadRufus** [twrackers/FadeLED-library#3]
First of all, I want to thank you @twrackers for making this neat little library publically available.

I was wondering if a getting started example could be included, to use the fade functionality.

Many thanks
Medad

**Comment by twrackers** [comment]
That's a good idea, I'm surprised I haven't done that already.  I'm out of
town until tomorrow evening, but there's a Micro Center here where I am, so
if I get a chance to swing by, I can grab a few moe parts... err...
*more* parts
and can whip up a quick test circuit.  The code will take me ~5 minutes,
but I'll want to test it before I post it to my GitHub.  Too bad the
LED_BUILTIN on most Arduinos is not PWM capable. 😓  If I don't do it
tonight, it'll definitely get done this weekend.

TWR

**Comment by twrackers** [comment]
Four example sketches have been added to this repository.

**Comment by MedadRufus** [comment]
Awesome Thanks!

Medad
